### ISSUE TITLE
Private Group? Public Address?

### ISSUE THREAD

**Issue by akaralar** [iOS-Developers-Slack/Code-Of-Conduct#4]
Hello,

Just saw this and googling didn't turn any results. Is it possible to get an invite to this slack organisation or is there a way to sign up somewhere?

Thanks!

**Comment by mergesort** [comment]
Hey akarala,

Right now it's a moderated group where people who are invited can invite someone who they feel would be a good fit for the chat. If/when that policy changes, I'll be sure to let you know. :smile:
